services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    image: bolagro-store:latest
    container_name: bolagro-backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/bolagro?sslmode=disable
      STORE_CORS: http://localhost:8000
      ADMIN_CORS: http://localhost:9000
      BACKEND_URL: http://localhost:9000
      REDIS_URL: redis://redis:6379
      ADMIN_MAIL: vatsik@i.ua
      ADMIN_PWD: vatsik
      NODE_ENV: development
    ports:
      - '9000:9000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/token']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # frontend:
  #   build:
  #     context: ./
  #     dockerfile: ./frontend/Dockerfile
  #   image: bolagro-store-frontend:latest
  #   container_name: bolagro-frontend
  #   restart: always
  #   environment:
  #     NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://backend:9000
  #     NEXT_PUBLIC_BASE_URL: http://localhost:8000
  #     NEXT_PUBLIC_DEFAULT_REGION: ua
  #     REVALIDATE_SECRET: supersecret
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   ports:
  #     - '8000:8000'

  postgres:
    restart: always
    image: postgres:16.4
    container_name: bolagro-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bolagro

  redis:
    image: redis
    container_name: bolagro-redis
    restart: always
    ports:
      - '6379:6379'